#!/bin/bash
# https://docs.docker.com/docker-cloud/builds/advanced/

set -xeo pipefail

GIT_TAG="$(git describe --tags "$(git rev-list --tags --max-count=1)")"

DOCKER_TAG="${GIT_TAG}"
if [[ "${DOCKER_TAG:0:1}" = v ]]; then
    DOCKER_TAG="${DOCKER_TAG:1}"
fi

docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${DOCKER_TAG}"
docker push "${DOCKER_REPO}:${DOCKER_TAG}"
